USE [master]
GO

/****** Object:  Database [Ticket_Log4net_Database]    Script Date: 01/26/2018 18:44:39 ******/
CREATE DATABASE [Ticket_Log4net_Database] ON  PRIMARY 
( NAME = N'Ticket_Log4net_Database', FILENAME = N'H:\data\Ticket_Log4net_Database.mdf' , SIZE = 1526464KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Ticket_Log4net_Database_log', FILENAME = N'H:\data\Ticket_Log4net_Database_log.ldf' , SIZE = 3840KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Ticket_Log4net_Database] ADD FILEGROUP [filegroup01]
GO

ALTER DATABASE [Ticket_Log4net_Database] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ticket_Log4net_Database].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [Ticket_Log4net_Database] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET ARITHABORT OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET  READ_WRITE 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET  MULTI_USER 
GO

ALTER DATABASE [Ticket_Log4net_Database] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Ticket_Log4net_Database] SET DB_CHAINING OFF 
GO


